/**
 * Supabase Generated Types
 *
 * This file will be auto-generated by:
 *   supabase gen types typescript --project-id <ref>
 *
 * Or via MCP: generate_typescript_types
 *
 * DO NOT EDIT MANUALLY — regenerate after each migration.
 */

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
